---
- hosts: ansiblenode1
  become: yes
  tasks:
  - name: Creates a file
    file: path=/home/ansible/firstplay.txt state=touch

- hosts: ansiblenode2
  become: yes
  tasks:
  - name: Creates a directory
    file: path=/home/ansible/firstplay state=directory


