---
- hosts: all
  become: yes
  gather_facts: no
  vars:
  - var1: variable1
  - var2: variable2
  tasks: 
  - name: task one var1
    shell: echo var1 >  one.txt
  - name: task two var2
    shell: echo value of var2 is {{ var2 }} > two.txt
  
