---
- hosts: all
  become: yes
  gather_facts: no
  vars:
  - var1: variable1
  vars_prompt:
  - name: var2
    prompt: enter variable for var2
  tasks:
  - name: task one
    shell: echo  var1 > one.txt
  - name: task two
    shell: echo "value of var2 is {{ var2 }}" > two.txt

