---
- hosts: all
  become: yes
  tasks:
  - name: Install apache2
    apt: name=apache2 state=present
  - name: Make Apache2 running and enabled
    service: name=apache2 state=started enabled=yes
  - name: Display Name on Apache web page
    copy: content="Lakshminarayanan" dest=/var/www/html/index.html
